### ISSUE TITLE
[PHP 8.2] Syntax Error in ScanService.php - Unexpected identifier "SCAN_TIME_SECONDS"

### ISSUE THREAD

**Issue by RedBloodDeadman** [GDATASoftwareAG/nextcloud-gdata-antivirus#226]
**Description:**
When running G DATA Antivirus 31.0.5 for Nextcloud 31.0.5 on PHP 8.2 (Debian Bookworm), a parse error occurs in 

> lib/Service/ScanService.php 

during cron execution:

`ParseError: syntax error, unexpected identifier "SCAN_TIME_SECONDS", expecting "=" in /var/www/html/nextcloud/apps/gdatavaas/lib/Service/ScanService.php:16`

**Steps to Reproduce:**

1. Run Nextcloud 31.0.5 on PHP 8.2 environment (Debian Bookworm)
2. Execute cron.php manually to trigger the error:
`php -f /var/www/html/nextcloud/cron.php`
3. The parse error appears immediately

**Error Details:**

File: 

> apps/gdatavaas/lib/Service/ScanService.php

Line: 16
Current problematic code:
`private const int SCAN_TIME_SECONDS = 120; `

**Expected Behavior:**
Cron jobs should execute without syntax errors and antivirus scans should run normally.

**Proposed Fix:**
Remove the type declaration to make it compatible with PHP 8.2:

`private const SCAN_TIME_SECONDS = 120;`

**Impact:**
- Blocks all cron-related functionality
- Prevents scheduled antivirus scans

**Environment:**
- G DATA Antivirus Version: 31.0.5
- Nextcloud Version: 31.0.5
- PHP Version: 8.2
- OS: Debian 12 (Bookworm)

**Verification Steps:**
1. Apply the fix
2. Run manually:
`php -f /var/www/html/nextcloud/cron.php`
3. Confirm:
-  No errors in output
-  Nextcloud admin shows successful cron execution
-  Antivirus scans execute as scheduled

**Additional Context:**
This appears to be a PHP version compatibility issue where the typed constant syntax isn't properly supported in this environment. The fix maintains identical functionality while resolving the syntax error.

**Comment by lennartdohmann** [comment]
Hi @RedBloodDeadman thanks for providing this issue! Should be fixed within the next release.

**Comment by lennartdohmann** [comment]
It would be very nice if you could confirm that the problem has been solved with the new version.

**Comment by RedBloodDeadman** [comment]
@lennartdohmann Thank you for the quick fix! However, I’d like to point out that the issue persists in version 31.0.6, while it has been resolved in 30.3.6.

**Comment by lennartdohmann** [comment]
Could this maybe be cache related I can not reproduce this. Is the error the exact same?

**Comment by RedBloodDeadman** [comment]
Yes, I checked the build downloaded from github. The file in the archive is unchanged.
https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/releases/download/31.0.6/gdatavaas.tar.gz

**Comment by lennartdohmann** [comment]
Version 31.0.6 is fixed now. Thanks!
